Interface updates
NIAEFEUP/Timetable-Selector-Old pull request #7
Opened 2017-08-28 21:58 UTC by msramalho

### Alterações: 
 1. Link para reiniciar - quando se carrega no logo (**Timetable Selector**) recarrega a página. A falta desta funcionalidade implicava fazer refresh à página para recomeçar, o que mesmo assim não funcionava depois de "Gravar Horário";
 2. Checkbox para mostrar/esconder práticas - pode parecer que não mas dá jeito, por vezes, ver apenas as aulas teóricas para ter noção de que parte do horário é que é inflexível;
 3. Melhorias no interface de cópia do link - agora é possível ver e esconder o link (mantive isto porque haverá browsers em que a cópia automática não funciona); implementei cópia automática para a área de transferência/clipboard (através do botão **Copiar Link**) que dá feedback sobre se copiou ou não; o link agora está sempre atualizado, não apenas quando o utilizador carrega no botão, desta forma podem sempre adicionar diretamente aos marcadores ou copiar o link sem haver dúvida sobre se o link corresponde à configuração atual, porque está sempre atualizado.

### Justificação
Estas alterações tornam a ferramenta mais user friendly 

### Nota
No ficheiro `TTS.js` o meu IDE reformatou o código js ligeiramente, e deixei ficar por ficar melhor estruturado e mais acessível para leitura, como poderão ver.

2017-08-28 23:07 UTC, bernardobelchior requested changes
Obrigado pelo teu contributo! Veio acrescentar algumas melhorias ao nível da experiência do utilizador, tenho apenas uns pequenos detalhes a apontar, mas não é um problema de maior. 
Antes de mais, espero que saibas que, atualmente, estamos a desenvolver uma nova versão do TimeTable Selector e, portanto, este código já não será assim tão interessante. 

Posto isto, deixei algumas anotações onde achei necessário. Só peço que, quando fizeres pull requests, tenta enviar menos mudanças de uma só vez. É preferível fazeres 4 pull requests, porque são fáceis de rever e aceitar logo, do que um enorme que demora muito tempo a ser aceite.
Estas críticas são apenas no sentido construtivo, espero que não as leves a mal, porque não é essa a intenção. 

Mais uma vez, obrigado pelo teu contributo e está atento à época de recrutamento do núcleo, caso estejas interessado!

Com os melhores cumprimentos,
Bernardo Belchior

PS: Reparei, também, que retiraste a animação da caixa dos links, alguma razão em especial?

2017-08-28 23:07 UTC, bernardobelchior commented on index.html
> +				<i id="copiedIcon" style="display:none;" class="icon-check" aria-hidden="true"> feito</i>
Esta informação parece um bocado fora do contexto visual. Com isto, quero dizer que parece um bocado anormal, no que é o design do site. Talvez acrescentar uma caixa vermelha por detrás ajude?

2017-08-28 23:07 UTC, bernardobelchior commented on TTS.css
> +	color: #FFFFFF;
Aqui, na minha opinião, uma melhor opção seria colocar a cor como "inherit", para que herde a cor do seu pai.
Isto, com a inversão da ordem de definição do anchor pode ser vantajoso caso o header mude de cor.

2017-08-28 23:07 UTC, bernardobelchior commented on index.html
> +		<img class="logo" src="logosmall.png"><a href="." class="noLink"><h1><i class="icon-table"></i> Timetable Selector</h1></a>
A inversão do header com o anchor seria mais correto, uma vez que pode haver utilizadores com navegadores que ainda não suportem HTML5, porque só nesta versão é que se pode utilizar, com segurança, o que tu colocaste. 
Se quiseres ler mais, vê [aqui](https://stackoverflow.com/questions/7023512/which-is-more-correct-h1a-a-h1-or-ah1-h1-a).

2017-08-28 23:07 UTC, bernardobelchior commented on TTS.js
> +    if (this.praticas.length != 0) str += '<label title="Alternar mostrar/esconder aulas práticas"><input class="mostrarpraticas" value="' + this.nome + '" type="checkbox" data-cadeira="' + this.nome
Boa adição! O único problema que vejo é que existe pouca distância entre o elemento das teóricas e o das práticas. Acho que uma margem à esquerda do segundo de 10px resolveria isso.

2017-08-29 09:47 UTC, msramalho commented
Quanto a ter retirado a animação, foi só para usar diretamente o `toggle`, nada de mais. 
Como já juntei isto tudo vou corrigir e fazer um novo pull com as alterações que mencionaste.

2017-08-29 09:47 UTC, msramalho commented on index.html
> +		<img class="logo" src="logosmall.png"><a href="." class="noLink"><h1><i class="icon-table"></i> Timetable Selector</h1></a>
eu sei disso e deixei por fora para tornar toda a área sujeita a cliques e para o caso de mudarem o atributo `display `do `h1`, não apenas o logo e o texto, mas mudar isso é rápido.

2017-08-29 09:48 UTC, msramalho commented on index.html
> +				<i id="copiedIcon" style="display:none;" class="icon-check" aria-hidden="true"> feito</i>
Só adicionei um botão, o da esquerda já lá estava e o design do site pouco se alterou. Não vou mexer mais nisto, porque prefiro não o fazer a não ficar como esperam.

2017-08-29 09:48 UTC, msramalho commented on TTS.css
> +	color: #FFFFFF;
:+1:

2017-08-29 09:50 UTC, msramalho commented on TTS.js
> +    if (this.praticas.length != 0) str += '<label title="Alternar mostrar/esconder aulas práticas"><input class="mostrarpraticas" value="' + this.nome + '" type="checkbox" data-cadeira="' + this.nome
vou adicionar essa regra, contudo `10px` pareceu-me pouco ao testar, e deixei `20px`.

2017-08-29 10:00 UTC, msramalho commented
já adicionei novamente a animação

2017-08-29 19:34 UTC, Misirlou approved these changes
É fixe ver malta a contribuir para isto. LGTM. 

Also, concordo com o Bernado quanto à divisão de PR's. Ter pelo menos um para fazer a reindentação ajudava bastante, mas como veio no 1º commit foi só filtrar esse fora.

2017-08-29 19:34 UTC, Misirlou commented on TTS.js
> +    var successful = document.execCommand('copy');
Bravo, na minha altura era só com flash, e preferia obrigar os utilizadores a fazer ctrl C ao URL do que usar flash no site.

2017-08-29 19:34 UTC, Misirlou commented on index.html
> +				<i id="copiedIcon" style="display:none;" class="icon-check" aria-hidden="true"> feito</i>
O botão está fixe. Se calhar tirava o "feito"/"falhou" e deixava só os ícones.

2017-08-30 10:22 UTC, msramalho commented on TTS.js
> +    var successful = document.execCommand('copy');
👍

2017-08-30 10:23 UTC, msramalho commented
Quanto ao feito falhou, acho que melo menos o falhou devia ficar, porque só o icon não é muito elucidativo. Foi por isso que deixei os dois, mas pensando bem, para o _feito_ não é necessário mostrar a mensagem

2017-09-01 11:11 UTC, msramalho commented
Acho que está pronto, @bernardobelchior

2017-09-04 22:04 UTC, merged

2017-09-04 22:08 UTC, bernardobelchior commented
Peguei nos ícones que estavas a utilizar e alterei o texto do botão "Copiar link" para "Link copiado com successo" ou "Erro ao copiar", dependendo da situação. Penso que assim a informação está mais dentro do contexto visual do site.
Peço, então, que, além de mim, verifiques também se está tudo funcional para que se possa colocar no servidor.

Boa iniciativa e mantém-te atento à nossa página do Facebook, dá-nos sempre jeito membro pro-ativos como tu ;)

Continua assim,
Bernardo Belchior

2017-09-12 09:52 UTC, msramalho commented
@bernardobelchior julgo que está pronto para pôr no servidor, eventualmente podia ser interessante ter também uma stack para fazer retroceder, ou para fazer reset e voltar ao estado incial em que o link foi aberto.
👍

2017-09-12 10:08 UTC, bernardobelchior commented
Isso são boas ideias, mas atualmente não faz muito sentido continuarmos a melhorar projetos que serão descontinuados. 
De qualquer das formas, obrigado! Iremos atualizar o servidor brevemente.